[workspace]
authors = ["Nassima Bouhenni <nhbouhenni@gmail.com>"]
channels = ["conda-forge"]
name = "2025"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
